version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-auth/web.yml:/etc/prometheus/web.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - LANG=pt_BR.UTF-8
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  fastapi-collector: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-collector
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
