global:
  scrape_interval: 5s  # Coleta métricas a cada 5 segundos
  evaluation_interval: 10s  # Avalia regras de alerta e gravação a cada 10 segundos

scrape_configs:
  - job_name: 'fastapi-exporter'
    static_configs:
      - targets: ['fastapi-exporter:8000']